on:
  pull_request:
    types: [opened, edited]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check action step
        id: check
        uses: tokghwt/my-js-action@v0
        with:
          pattern: '^(?:feat!?|fix!?|refactor|release|docs|test|chore|revert)(?:\([^)]+\))?: [A-Z].*[^ ]$'
