on:
  push:
    branches: [main]
jobs:
  merge_commit_message_check:
    runs-on: ubuntu-latest
    steps:
      - uses: tokghwt/my-js-action@v0
        with:
          pattern: '^(?:(?:feat!?|fix!?|refactor|docs|test|chore)(?:\([^)]+\))?: [A-Z].*[^ ]|release: v[0-9]+\.[0-9]+\.[0-9]+|revert: ".+") \(#[1-9][0-9]*\)$'
